# Generated by Django 2.2.3 on 2019-07-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('authour_name', models.CharField(max_length=30)),
                ('book_price', models.IntegerField()),
                ('book_code', models.IntegerField()),
            ],
            options={
                'db_table': 'book_details',
            },
        ),
    ]
